//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module minilab1b(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output	reg     [6:0]		HEX0,
	output	reg     [6:0]		HEX1,
	output	reg     [6:0]		HEX2,
	output	reg     [6:0]		HEX3,
	output	reg     [6:0]		HEX4,
	output	reg     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output	reg	     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);

localparam EXEC = 1'b0;
localparam DONE = 1'b1;

parameter HEX_0  = 7'b1000000;	// zero
parameter HEX_1  = 7'b1111001;	// one
parameter HEX_2  = 7'b0100100;	// two
parameter HEX_3  = 7'b0110000;	// three
parameter HEX_4  = 7'b0011001;	// four
parameter HEX_5  = 7'b0010010;	// five
parameter HEX_6  = 7'b0000010;	// six
parameter HEX_7  = 7'b1111000;	// seven
parameter HEX_8  = 7'b0000000;	// eight
parameter HEX_9  = 7'b0011000;	// nine
parameter HEX_10 = 7'b0001000;	// ten : a
parameter HEX_11 = 7'b0000011;	// eleven : b
parameter HEX_12 = 7'b1000110;	// twelve : c
parameter HEX_13 = 7'b0100001;	// thirteen : d
parameter HEX_14 = 7'b0000110;	// fourteen : e
parameter HEX_15 = 7'b0001110;	// fifteen : f
parameter OFF    = 7'b1111111;	// all off

//=======================================================
//  REG/WIRE declarations
//=======================================================
reg         state;
wire        rst_n;
reg  [3:0]  result_index;

wire        done;
wire [23:0] result0;
wire [23:0] result1;
wire [23:0] result2;
wire [23:0] result3;
wire [23:0] result4;
wire [23:0] result5;
wire [23:0] result6;
wire [23:0] result7;

reg [23:0] mvm_result [7:0];
wire [1:0] state_led;


//=======================================================
//  Module instantiation
//=======================================================

minilab1b_exec minilab1b(.clk(CLOCK_50), .rst_n(rst_n), .done(done), 
						 .result0(result0), .result1(result1), .result2(result2), .result3(result3), 
						 .result4(result4), .result5(result5), .result6(result6), .result7(result7), .state_led(state_led));

//=======================================================
//  Structural coding
//=======================================================

assign rst_n = KEY[0];

always @(posedge CLOCK_50 or negedge rst_n) begin
  if (~rst_n) begin
    state <= EXEC;
  end
  else begin
    case(state)
	   	EXEC : begin
		  if(done) begin
			state <= DONE;
		  end
	   	end	
		DONE : begin
			mvm_result[0] <= result0;
			mvm_result[1] <= result1;
			mvm_result[2] <= result2;
			mvm_result[3] <= result3;
			mvm_result[4] <= result4;
			mvm_result[5] <= result5;
			mvm_result[6] <= result6;
			mvm_result[7] <= result7;
		end
	 endcase
  end
end


always @(*) begin
	case(SW)
		10'b00_0000_0001 : begin
			result_index = 4'd0;
		end
		10'b00_0000_0010 : begin
			result_index = 4'd1;
		end
		10'b00_0000_0100 : begin
			result_index = 4'd2;
		end
		10'b00_0000_1000 : begin
			result_index = 4'd3;
		end
		10'b00_0001_0000 : begin
			result_index = 4'd4;
		end
		10'b00_0010_0000 : begin
			result_index = 4'd5;
		end
		10'b00_0100_0000 : begin
			result_index = 4'd6;
		end
		10'b00_1000_0000 : begin
			result_index = 4'd7;
		end
		default : begin
			result_index = 4'd0;
		end
	endcase
end

always @(*) begin
  if (state == DONE & SW[result_index]) begin
    case(mvm_result[result_index][3:0])
      4'd0: HEX0 = HEX_0;
	   4'd1: HEX0 = HEX_1;
	   4'd2: HEX0 = HEX_2;
	   4'd3: HEX0 = HEX_3;
	   4'd4: HEX0 = HEX_4;
	   4'd5: HEX0 = HEX_5;
	   4'd6: HEX0 = HEX_6;
	   4'd7: HEX0 = HEX_7;
	   4'd8: HEX0 = HEX_8;
	   4'd9: HEX0 = HEX_9;
	   4'd10: HEX0 = HEX_10;
	   4'd11: HEX0 = HEX_11;
	   4'd12: HEX0 = HEX_12;
	   4'd13: HEX0 = HEX_13;
	   4'd14: HEX0 = HEX_14;
	   4'd15: HEX0 = HEX_15;
    endcase
  end
  else begin
    HEX0 = OFF;
  end
end

always @(*) begin
  if (state == DONE & SW[result_index]) begin
    case(mvm_result[result_index][7:4])
      4'd0: HEX1 = HEX_0;
	   4'd1: HEX1 = HEX_1;
	   4'd2: HEX1 = HEX_2;
	   4'd3: HEX1 = HEX_3;
	   4'd4: HEX1 = HEX_4;
	   4'd5: HEX1 = HEX_5;
	   4'd6: HEX1 = HEX_6;
	   4'd7: HEX1 = HEX_7;
	   4'd8: HEX1 = HEX_8;
	   4'd9: HEX1 = HEX_9;
	   4'd10: HEX1 = HEX_10;
	   4'd11: HEX1 = HEX_11;
	   4'd12: HEX1 = HEX_12;
	   4'd13: HEX1 = HEX_13;
	   4'd14: HEX1 = HEX_14;
	   4'd15: HEX1 = HEX_15;
    endcase
  end
  else begin
    HEX1 = OFF;
  end
end

always @(*) begin
  if (state == DONE & SW[result_index]) begin
    case(mvm_result[result_index][11:8])
      4'd0: HEX2 = HEX_0;
	   4'd1: HEX2 = HEX_1;
	   4'd2: HEX2 = HEX_2;
	   4'd3: HEX2 = HEX_3;
	   4'd4: HEX2 = HEX_4;
	   4'd5: HEX2 = HEX_5;
	   4'd6: HEX2 = HEX_6;
	   4'd7: HEX2 = HEX_7;
	   4'd8: HEX2 = HEX_8;
	   4'd9: HEX2 = HEX_9;
	   4'd10: HEX2 = HEX_10;
	   4'd11: HEX2 = HEX_11;
	   4'd12: HEX2 = HEX_12;
	   4'd13: HEX2 = HEX_13;
	   4'd14: HEX2 = HEX_14;
	   4'd15: HEX2 = HEX_15;
    endcase
  end
  else begin
    HEX2 = OFF;
  end
end

always @(*) begin
  if (state == DONE & SW[result_index]) begin
    case(mvm_result[result_index][15:12])
      4'd0: HEX3 = HEX_0;
	   4'd1: HEX3 = HEX_1;
	   4'd2: HEX3 = HEX_2;
	   4'd3: HEX3 = HEX_3;
	   4'd4: HEX3 = HEX_4;
	   4'd5: HEX3 = HEX_5;
	   4'd6: HEX3 = HEX_6;
	   4'd7: HEX3 = HEX_7;
	   4'd8: HEX3 = HEX_8;
	   4'd9: HEX3 = HEX_9;
	   4'd10: HEX3 = HEX_10;
	   4'd11: HEX3 = HEX_11;
	   4'd12: HEX3 = HEX_12;
	   4'd13: HEX3 = HEX_13;
	   4'd14: HEX3 = HEX_14;
	   4'd15: HEX3 = HEX_15;
    endcase
  end
  else begin
    HEX3 = OFF;
  end
end

always @(*) begin
  if (state == DONE & SW[result_index]) begin
    case(mvm_result[result_index][19:16])
      4'd0: HEX4 = HEX_0;
	   4'd1: HEX4 = HEX_1;
	   4'd2: HEX4 = HEX_2;
	   4'd3: HEX4 = HEX_3;
	   4'd4: HEX4 = HEX_4;
	   4'd5: HEX4 = HEX_5;
	   4'd6: HEX4 = HEX_6;
	   4'd7: HEX4 = HEX_7;
	   4'd8: HEX4 = HEX_8;
	   4'd9: HEX4 = HEX_9;
	   4'd10: HEX4 = HEX_10;
	   4'd11: HEX4 = HEX_11;
	   4'd12: HEX4 = HEX_12;
	   4'd13: HEX4 = HEX_13;
	   4'd14: HEX4 = HEX_14;
	   4'd15: HEX4 = HEX_15;
    endcase
  end
  else begin
    HEX4 = OFF;
  end
end

always @(*) begin
  if (state == DONE & SW[result_index]) begin
    case(mvm_result[result_index][23:20])
      4'd0: HEX5 = HEX_0;
	   4'd1: HEX5 = HEX_1;
	   4'd2: HEX5 = HEX_2;
	   4'd3: HEX5 = HEX_3;
	   4'd4: HEX5 = HEX_4;
	   4'd5: HEX5 = HEX_5;
	   4'd6: HEX5 = HEX_6;
	   4'd7: HEX5 = HEX_7;
	   4'd8: HEX5 = HEX_8;
	   4'd9: HEX5 = HEX_9;
	   4'd10: HEX5 = HEX_10;
	   4'd11: HEX5 = HEX_11;
	   4'd12: HEX5 = HEX_12;
	   4'd13: HEX5 = HEX_13;
	   4'd14: HEX5 = HEX_14;
	   4'd15: HEX5 = HEX_15;
    endcase
  end
  else begin
    HEX5 = OFF;
  end
end

always @(*) begin
	case(state_led)
		2'b00 : begin
			LEDR = {{8{1'b0}}, 1'b1};
		end
		2'b01 : begin
			LEDR = {{7{1'b0}}, 1'b1, 1'b0};
		end
		2'b10 : begin
			LEDR = {{6{1'b0}}, 1'b1, {2{1'b0}}};
		end
		default : begin
			LEDR = {{6{1'b0}}, 1'b1, {2{1'b0}}};
		end
	endcase
end
endmodule

